sudo: required

services:
    - docker

env: 
    - FENICS_VERSION=2018.1
    - FENICS_VERSION=2019.1

before_install: ./ci/run_before_install.sh

script: ./ci/run_unittest.sh

jobs:
    include:
        - stage: test
          script: ./ci/run_scripts.sh
          env: FENICS_VERSION=2018.1
        - stage: test
          script: ./ci/run_scripts.sh
          env: FENICS_VERSION=2019.1

